### PR TITLE
Add name to license to make Github recognize it.

### PR DESCRIPTION
**Pull request by gdziadkiewicz**
It helps to learn what to expect on the first glance plus GitHub use it for statistics and as search feature.

Before:
image
After:
image

### CODE REVIEW

**Comment by gdziadkiewicz** [comment]
@txsmith I plan to use this project and add missing features that I need. Are you interested in accepting PRs or should I just work on my own fork?

**Comment by txsmith** [comment]
I'm currently no longer doing anything with this repo and I'm not sure I can find the time to moderate PRs effectively, but I'd be happy to transfer ownership to you if you'd like!

**Comment by gdziadkiewicz** [comment]
@txsmith that would be great - happy to accept the transfer

**Comment by txsmith** [comment]
I think you need to rename or delete your fork first for this to happen, GitHub complains that gdziadkiewicz/philips-hue-haskell already exists

**Comment by gdziadkiewicz** [comment]
I deleted the fork. Could you retry?

**Pull request merged**
